name: Build

on:
  pull_request:
    types: [ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.2.2

      - name: Clean and Install
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test:action

      - name: Jest coverage comment
        uses: MishaKav/jest-coverage-comment@14d08a64515f6fd4b28ae6a67c5c43364cea1357 # v1.0.95
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
          title: Pull Request Coverage - By CreativeCode.com.co
          summary-title: Pull Request Summary
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          junitxml-title: Tests Details
          junitxml-path: ./junit.xml
          coverage-title: Coverage by file
          coverage-path: ./coverage.txt
